spring:
  application:
    name: microservice-product-config

    #name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8 # 数据
    #库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.mengxuegu.springcloud.entities # 所有Entity别名类所在包
    #mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件
  mapper-locations: classpath:mapper/**/*.xml # mapper映射文件

server:
  port: 8052

